books-progress-tracking-hotwire-app/config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "books#index"
  
  resources :books, except: [ :index ]

  resources :read_runs do
    member do
      post :new
    end
  end

  resources :read_sessions do
    member do
      post :new
      post :edit
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

books-progress-tracking-hotwire-app/app/models/book.rb
class Book < ApplicationRecord
  has_many :read_runs, -> { order(:created_at => :desc) }

  validates :title, :author, :pages, presence: true
  validates :title, uniqueness: { case_sensitive: false }
end

books-progress-tracking-hotwire-app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
    # avoid n+1 queries
    @book = Book.includes(read_runs: [ :read_sessions ]).find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.turbo_stream { render :create, locals: { book: @book } }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity, locals: { book: @book } }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :pages, :published, :image)
    end
end

books-progress-tracking-hotwire-app/app/helpers/books_helper.rb
module BooksHelper
end

books-progress-tracking-hotwire-app/app/views/books/_book.html.erb
<div id="<%= dom_id book %>" class="card">
  <img class="rounded" src="<%= book.image %>" alt="book image" />
  <div class="card-body">
    <p class="card-text">
      <table class="table">
        <tbody>
          <tr>
            <td>Title:</td>
            <td><%= book.title %></td>
          </tr>
          <tr>
            <td>Author:</td>
            <td><%= book.author %></td>
          </tr>
          <tr>
            <td>Pages:</td>
            <td><%= book.pages %></td>
          </tr>
          <tr>
            <td>Published:</td>
            <td><%= book.published %></td>
          </tr>
        </tbody>
      </table>
    </p>
  </div>
</div>

books-progress-tracking-hotwire-app/app/views/books/_book_card.html.erb
<div class="book">
  <%= link_to book do %>
    <div class="card">
      <img class="rounded" src="<%= book.image %>" alt="book image" />
      <div class="card-body">
        <p class="card-text"><%= book.title %></p>
      </div>
    </div>
  <% end %>
</div>

books-progress-tracking-hotwire-app/app/views/books/_form.html.erb
<div class="container">
  <div class="row">
    <%= form_with(model: book) do |form| %>
      <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control #{is_field_invalid?(book, :title)}" %>
      </div>
    
      <div class="mb-3">
        <%= form.label :author, class: "form-label" %>
        <%= form.text_field :author, class: "form-control #{is_field_invalid?(book, :author)}" %>
      </div>
    
      <div class="mb-3">
        <%= form.label :pages, class: "form-label" %>
        <%= form.number_field :pages, class: "form-control #{is_field_invalid?(book, :pages)}" %>
      </div>
    
      <div class="mb-3">
        <%= form.label :published, class: "form-label" %>
        <%= form.date_field :published, class: "form-control" %>
      </div>
    
      <div class="mb-3">
        <%= form.label :image, class: "form-label" %>
        <%= form.text_field :image, class: "form-control" %>
      </div>
    
      <div class="mb-3 text-end">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Close</button>
        <%= form.submit "Create", class: "btn btn-primary", 'data-bs-dismiss': "modal" %>
      </div>
    <% end %>
  </div>
</div>

books-progress-tracking-hotwire-app/app/views/books/_new.html.erb
<%= render "form", book: @book %>

books-progress-tracking-hotwire-app/app/views/books/create.turbo_stream.erb
<%= turbo_stream.append "books", partial: "books/book_card", locals: { book: book } %>

books-progress-tracking-hotwire-app/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

books-progress-tracking-hotwire-app/app/views/books/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Home</li>
  </ol>
</nav>

<div>
  <div id="actions">
    <%= link_to "Add Book", new_book_path, class: "btn btn-primary", data: { turbo_frame: "modal" } %>
  </div>

  <%= turbo_frame_tag "books_frame", data: { turbo: false } do %>
    <div id="books">
      <% @books.each do |book| %>
        <%= render partial: "books/book_card", locals: { book: book } %>
      <% end %>
    </div>
  <% end %>
</div>

books-progress-tracking-hotwire-app/app/views/books/new.html+turbo_frame.erb
<%= turbo_frame_tag "modal" do %>
  <%= render_modal title: "New Book", body: "books/new" %>
<% end %>

books-progress-tracking-hotwire-app/app/views/books/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= render_modal title: "New Book", body: "books/new" %>
<% end %>

books-progress-tracking-hotwire-app/app/views/books/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @book.title %></li>
  </ol>
</nav>

<div class="content">
  <div class="row">
    <div class="col-md-3">
      <%= render partial: "books/book", locals: { book: @book } %>
    </div>
    <div class="col-md-9">
      <%= render template: "read_runs/index", locals: { book: @book, read_runs: @book.read_runs } %>
    </div>
  </div>
</div>