books-progress-tracking-hotwire-app/config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "books#index"
  
  resources :books, except: [ :index ]

  resources :read_runs do
    member do
      post :new
    end
  end

  resources :read_sessions do
    member do
      post :new
      post :edit
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

books-progress-tracking-hotwire-app/app/models/read_run.rb
class ReadRun < ApplicationRecord
  enum status: [ :open, :completed ]

  belongs_to :book
  has_many :read_sessions, -> { order(:created_at => :desc) }

  validates :book, :status, :run_number, presence: true
  validates :run_number, uniqueness: { scope: :book_id }
end

books-progress-tracking-hotwire-app/app/controllers/read_runs_controller.rb
class ReadRunsController < ApplicationController
  before_action :set_read_run, only: %i[ show edit update destroy ]

  # GET /read_runs or /read_runs.json
  def index
    @read_runs = ReadRun.all.order(created_at: :desc)
  end

  # GET /read_runs/1 or /read_runs/1.json
  def show
  end

  # GET /read_runs/new
  def new
    @book = Book.find(params[:book_id])
    
    @read_run = ReadRun.new
    @read_run.run_number = @book.read_runs.count + 1
    @read_run.book = @book

    respond_to do |format|
      format.turbo_stream { render :new, locals: { read_run: @read_run } }
    end
  end

  # GET /read_runs/1/edit
  def edit
  end

  # POST /read_runs or /read_runs.json
  def create
    @read_run = ReadRun.new(read_run_params)

    respond_to do |format|
      if @read_run.save
        format.turbo_stream { render :create, locals: { read_run: @read_run } }
        format.json { render :show, status: :created, location: @read_run }
      else
        format.turbo_stream { render :new, status: :unprocessable_entity, locals: { read_run: @read_run } }
        format.json { render json: @read_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /read_runs/1 or /read_runs/1.json
  def update
    respond_to do |format|
      if @read_run.update(read_run_params)
        format.html { redirect_to read_run_url(@read_run), notice: "Read run was successfully updated." }
        format.json { render :show, status: :ok, location: @read_run }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @read_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /read_runs/1 or /read_runs/1.json
  def destroy
    @read_run.destroy!

    respond_to do |format|
      format.turbo_stream { render :destroy, locals: { read_run: @read_run } }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_read_run
      @read_run = ReadRun.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def read_run_params
      params.require(:read_run).permit(:run_number, :status, :book_id)
    end
end

books-progress-tracking-hotwire-app/app/helpers/read_runs_helper.rb
module ReadRunsHelper
  def get_total_read_pages(read_run)
    read_run.read_sessions.map(&:read_pages).inject(0, :+)
  end

  def calculate_read_percentage(read_run, total_read_pages)
    pages = read_run.book.pages
    remaining_pages = pages - total_read_pages
    read_percentage = (100 * (pages - remaining_pages) / pages)

    read_percentage
  end
end

books-progress-tracking-hotwire-app/app/views/read_runs/_form.html.erb
<%= turbo_frame_tag "read_run_form" do %>
  <%= form_with(model: read_run) do |form| %>
    <div id="<%= dom_id read_run %>" class="list-group" style="margin: 0.5em 0;">
      <li class="list-group-item list-group-item-dark" aria-current="true">
        <div class="row">
          <div class="col-4">
            <div class="form-group">
              <%= form.number_field :run_number, class: "form-control #{is_field_invalid?(read_run, :run_number)}", placeholder: "Run number" %>
            </div>
          </div>
          <div class="col-5">
            <div class="form-group">
              <%= form.select :status, options_for_select(
                  ReadRun.statuses.map {|key, value| [key.humanize.capitalize, ReadRun.statuses.key(value)]}, read_run.status
                ), {}, { class: "form-select" } %>
            </div>
          </div>
          <div class="col-3 text-end">
            <%= form.hidden_field :book_id, value: read_run.book_id %>
            <%= link_to "Cancel", :back, class: "btn btn-secondary btn-sm", data: { turbo_frame: "_top" } %>
            <%= form.submit "Create", class: "btn btn-success btn-sm" %>
          </div>
        </div>
      </li>
    </div>
  <% end %>
<% end %>

books-progress-tracking-hotwire-app/app/views/read_runs/_progress_bar.html.erb
<%= turbo_frame_tag "progress_#{dom_id read_run}" do %>
  <% read_percentage = calculate_read_percentage(read_run, total_read_pages) %>
  <div class="progress" role="progressbar" aria-label="Example with label" aria-valuenow="<%= read_percentage %>" aria-valuemin="0" aria-valuemax="100">
    <div class="progress-bar" style="width: <%= read_percentage %>%"><%= read_percentage %>%</div>
  </div>
<% end %>

books-progress-tracking-hotwire-app/app/views/read_runs/_read_run.html.erb
<div id="<%= dom_id read_run %>" class="list-group" style="margin: 1em 0;">
  <li class="list-group-item list-group-item-dark" aria-current="true">
    <div class="row">
      <div class="col-2">
        Run: <%= read_run.run_number %>
      </div>
      <div class="col-6">
        <%= turbo_frame_tag "progress_#{dom_id read_run}" do %>
          <%= render partial: "read_runs/progress_bar", locals: { read_run: read_run, total_read_pages: total_read_pages } %>
        <% end %>
      </div>
      <div class="col-3 text-end">
        Status: <%= read_run.status.capitalize %>
      </div>
      <div class="col-1 text-end">
        <%= button_to read_run_path(read_run), method: :delete, class: "btn btn-danger btn-sm" do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>
    </div>
  </li>
  <%= turbo_frame_tag id="sessions_#{dom_id read_run}" do %>
    <% read_run.read_sessions.each do |read_session| %>
      <%= render partial: "read_sessions/read_session", locals: { read_session: read_session } %>
    <% end %>
  <% end %>
  <li class="list-group-item">
    <div class="row">
      <div class="text-end">
        <%= button_to "Add Session", new_read_session_path(read_run_id: read_run.id), class: "btn btn-info btn-sm" %>
      </div>
    </div>
  </li>
</div>

books-progress-tracking-hotwire-app/app/views/read_runs/create.turbo_stream.erb
<%= turbo_stream.prepend "read_runs", partial: "read_runs/read_run", locals: { read_run: read_run, total_read_pages: get_total_read_pages(read_run) } %>
<%= turbo_stream.remove "read_run_form" %>

books-progress-tracking-hotwire-app/app/views/read_runs/destroy.turbo_stream.erb
<%= turbo_stream.remove("#{dom_id read_run}") %>

books-progress-tracking-hotwire-app/app/views/read_runs/edit.html.erb
<h1>Editing read run</h1>

<%= render "form", read_run: @read_run %>

<br>

<div>
  <%= link_to "Show this read run", @read_run %> |
  <%= link_to "Back to read runs", read_runs_path %>
</div>

books-progress-tracking-hotwire-app/app/views/read_runs/index.html.erb
<div id="actions">
  <%= button_to "Add Read Run", new_read_run_path(book_id: book.id), class: "btn btn-primary"%>
</div>

<%= turbo_frame_tag :read_runs do %>
  <% read_runs.each do |read_run| %>
    <%= render partial: "read_runs/read_run", locals: { read_run: read_run, total_read_pages: get_total_read_pages(read_run) } %>
  <% end %>
<% end %>

books-progress-tracking-hotwire-app/app/views/read_runs/new.turbo_stream.erb
<%= turbo_stream.prepend "read_runs", partial: "form", locals: { read_run: @read_run } %>

books-progress-tracking-hotwire-app/app/views/read_runs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @read_run %>

<div>
  <%= link_to "Edit this read run", edit_read_run_path(@read_run) %> |
  <%= link_to "Back to read runs", read_runs_path %>

  <%= button_to "Destroy this read run", @read_run, method: :delete %>
</div>