books-progress-tracking-hotwire-app/config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "books#index"
  
  resources :books, except: [ :index ]

  resources :read_runs do
    member do
      post :new
    end
  end

  resources :read_sessions do
    member do
      post :new
      post :edit
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

books-progress-tracking-hotwire-app/app/models/read_session.rb
class ReadSession < ApplicationRecord
  belongs_to :read_run

  validates :read_pages, presence: true
end

books-progress-tracking-hotwire-app/app/controllers/read_sessions_controller.rb
class ReadSessionsController < ApplicationController
  before_action :set_read_session, only: %i[ show edit update destroy ]

  helper ReadRunsHelper

  # GET /read_sessions or /read_sessions.json
  def index
    @read_sessions = ReadSession.all
  end

  # GET /read_sessions/1 or /read_sessions/1.json
  def show
  end

  # GET /read_sessions/new
  def new
    @read_session = ReadSession.new
    @read_run = ReadRun.find(params[:read_run_id])
    @read_session.read_run_id = params[:read_run_id]

    respond_to do |format|
      format.turbo_stream { render :new, locals: { read_session: @read_session, read_run: @read_run } }
    end
  end

  # GET /read_sessions/1/edit
  def edit
    respond_to do |format|
      format.turbo_stream { render :edit, locals: { read_session: @read_session } }
    end
  end

  # POST /read_sessions or /read_sessions.json
  def create
    @read_session = ReadSession.new(read_session_params)

    respond_to do |format|
      if @read_session.save
        format.turbo_stream { render :create, locals: { read_session: @read_session } }
        format.json { render :show, status: :created, location: @read_session }
      else
        format.turbo_stream { render :new, status: :unprocessable_entity, locals: { read_session: @read_session, read_run: @read_session.read_run } }
        format.json { render json: @read_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /read_sessions/1 or /read_sessions/1.json
  def update
    respond_to do |format|
      if @read_session.update(read_session_params)
        format.turbo_stream { render :update, locals: { read_session: @read_session } }
        format.json { render :show, status: :ok, location: @read_session }
      else
        format.turbo_stream { render :edit, status: :unprocessable_entity, locals: { read_session: @read_session, read_run: @read_session.read_run } }
        format.json { render json: @read_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /read_sessions/1 or /read_sessions/1.json
  def destroy
    @read_session.destroy!

    respond_to do |format|
      format.turbo_stream { render :destroy, locals: { read_session: @read_session } }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_read_session
      @read_session = ReadSession.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def read_session_params
      params.require(:read_session).permit(:read_pages, :read_run_id)
    end
end

books-progress-tracking-hotwire-app/app/helpers/read_sessions_helper.rb
module ReadSessionsHelper
end

books-progress-tracking-hotwire-app/app/views/read_sessions/_form.html.erb
<%= turbo_frame_tag "read_session_form_#{dom_id read_run}" do %>
  <%= form_with(model: read_session) do |form| %>
    <li id="<%= dom_id read_session %>" class="list-group-item">
      <div class="row">
        <div class="col-6">
          <div class="form-group">
            <%= form.number_field :read_pages, class: "form-control #{is_field_invalid?(read_session, :read_pages)}", placeholder: "Read pages" %>
          </div>
        </div>
        <div class="col-6 text-end">
          <%= form.hidden_field :read_run_id, value: read_session.read_run_id %>
          <%= link_to "Cancel", :back, class: "btn btn-secondary btn-sm", data: { turbo_frame: "_top" } %>
          <%= form.submit class: "btn btn-success btn-sm" %>
        </div>
      </div>
    </li>
  <% end %>
<% end %>

books-progress-tracking-hotwire-app/app/views/read_sessions/_read_session.html.erb
<li id="<%= dom_id read_session %>" class="list-group-item">
  <div class="row">
    <div class="col-4">
      <strong>Read pages:</strong> <%= read_session.read_pages %>
    </div>
    <div class="col-6">
      <strong>Recorded at:</strong> <%= read_session.created_at.strftime("%A %d, %B, %Y") %>
    </div>
    <div class="col-2 text-end">
      <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4">
          <%= button_to edit_read_session_path(read_session), class: "btn btn-light btn-sm" do %>
            <i class="fa-solid fa-pen-to-square"></i>
          <% end %>
        </div>
        <div class="col-4">
          <%= button_to read_session_path(read_session), method: :delete, class: "btn btn-danger btn-sm" do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li>

books-progress-tracking-hotwire-app/app/views/read_sessions/create.turbo_stream.erb
<%= turbo_stream.prepend "sessions_#{dom_id read_session.read_run}", partial: "read_sessions/read_session", locals: { read_session: read_session } %>
<%= turbo_stream.update("progress_#{dom_id read_session.read_run}", partial: "read_runs/progress_bar", locals: { read_run: read_session.read_run, total_read_pages: get_total_read_pages(read_session.read_run) }) %>
<%= turbo_stream.remove "read_session_form_#{dom_id read_session.read_run}" %>

books-progress-tracking-hotwire-app/app/views/read_sessions/destroy.turbo_stream.erb
<%= turbo_stream.remove("#{dom_id read_session}") %>
<%= turbo_stream.update("progress_#{dom_id read_session.read_run}", partial: "read_runs/progress_bar", locals: { read_run: read_session.read_run, total_read_pages: get_total_read_pages(read_session.read_run) }) %>

books-progress-tracking-hotwire-app/app/views/read_sessions/edit.html.erb
<h1>Editing read session</h1>

<%= render "form", read_session: @read_session %>

<br>

<div>
  <%= link_to "Show this read session", @read_session %> |
  <%= link_to "Back to read sessions", read_sessions_path %>
</div>

books-progress-tracking-hotwire-app/app/views/read_sessions/edit.turbo_stream.erb
<%= turbo_stream.update("#{dom_id read_session}", partial: "read_sessions/form", locals: { read_session: read_session, read_run: read_session.read_run }) %>

books-progress-tracking-hotwire-app/app/views/read_sessions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Read sessions</h1>

<div id="read_sessions">
  <% @read_sessions.each do |read_session| %>
    <%= render read_session %>
    <p>
      <%= link_to "Show this read session", read_session %>
    </p>
  <% end %>
</div>

<%= link_to "New read session", new_read_session_path %>

books-progress-tracking-hotwire-app/app/views/read_sessions/new.html.erb
<h1>New read session</h1>

<%= render "form", read_session: @read_session %>

<br>

<div>
  <%= link_to "Back to read sessions", read_sessions_path %>
</div>

books-progress-tracking-hotwire-app/app/views/read_sessions/new.turbo_stream.erb
<%= turbo_stream.prepend "sessions_#{dom_id read_session.read_run}", partial: "form", locals: { read_session: read_session, read_run: read_run } %>

books-progress-tracking-hotwire-app/app/views/read_sessions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @read_session %>

<div>
  <%= link_to "Edit this read session", edit_read_session_path(@read_session) %> |
  <%= link_to "Back to read sessions", read_sessions_path %>

  <%= button_to "Destroy this read session", @read_session, method: :delete %>
</div>

books-progress-tracking-hotwire-app/app/views/read_sessions/update.turbo_stream.erb
<%= turbo_stream.replace("#{dom_id read_session}", partial: "read_sessions/read_session", locals: { read_session: read_session }) %>
<%= turbo_stream.update("progress_#{dom_id read_session.read_run}", partial: "read_runs/progress_bar", locals: { read_run: read_session.read_run, total_read_pages: get_total_read_pages(read_session.read_run) }) %>